Improve error messages
The proc_macro_diagnostics feature would allow us to print out useful
spans and things handily, but until this, this provides a bunch more
contextutal information which will hopefully be useful to people.

New example output:
```
error: Can't generate num_enum traits for Foo because it does not have a valid `#[repr]` attribute.
error: proc-macro derive panicked
 --> src/main.rs:3:32
  |
3 | #[derive(Debug, Eq, PartialEq, TryFromPrimitive)]
  |                                ^^^^^^^^^^^^^^^^
  |
  = help: message: Can't generate num_enum traits for Foo because it does not have a valid `#[repr]` attribute.
```

Fixes #2